import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Landing page</h1>
        <Link href="/login">Log In</Link>
        <Link href="/signup">Sign Up</Link>
      </main>
    </div>
  )
}
